name: khateb_country_helper
description: >-
  Flutter country picker with SVG flags, single & multi-select bottom sheet,
  multilingual (AR/EN/TR), dial code lookup, and phone length validation.
version: 1.0.4
homepage: https://github.com/Mohammed-Khateb-github/khateb_country_helper
repository: https://github.com/Mohammed-Khateb-github/khateb_country_helper
issue_tracker: https://github.com/Mohammed-Khateb-github/khateb_country_helper/issues

screenshots:
  - description: 'Single Country Picker Light Green'
    path: screenshots/light_green.jpg
  - description: 'Single Country Picker Light Yellow'
    path: screenshots/light_yellow.jpg
  - description: 'Single Country Picker Dark Yellow'
    path: screenshots/dark_yellow.jpg
  - description: 'Multi Country Picker Light'
    path: screenshots/multiple_light.jpg
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  jovial_svg: ^1.1.20

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/si/
